# Lista de arquivos-fonte
SRCS = main.c 

# Nome do executável
EXEC = main

# Alvo padrão: compila o executável
all: $(EXEC)

# Regra de compilação
$(EXEC): $(SRCS)
	gcc $(SRCS) -o $(EXEC)

# Limpeza
clean:
	rm -f $(EXEC)

